# Generated by Django 2.2.6 on 2019-12-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citys',
            name='name',
            field=models.CharField(default='delhi', max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(default='leg', max_length=50),
        ),
    ]
